### ISSUE TITLE
Installation difficulty on mac

### ISSUE THREAD

**Issue by twalk4821** [LucaFulchir/libRaptorQ#13]
I am having trouble compiling this on mac. I checked out release 1.9, and using the default c and cpp compilers that come built in with the mac developer tools, I ran into this error:
```
clang: error: invalid linker name in argument '-fuse-ld=gold'
```
I thought I might try using a different compiler, so I installed the llvm toolset. ***By the way, I have not spent much time with c or c++ so I am not too familiar with any of this software***

Now strangely the error is a new one: 
```
[ 32%] Linking CXX static library libRaptorQ_Static_Profiling.a
Error running link command: No such file or directory
```

I have not deviated much from the installation instructions, except fiddling with a few environment variables. I guess this has to do with the different build environment on a mac?

**Comment by LucaFulchir** [comment]
Uhm... I do not have a MAC to run tests on, it's been a while since the last osx test.

But is seems the compilation was successful, and the linking failed, since you don't have the gold linker installed. Which should not be a problem, because in this case it should default to the BSD linker which is always available.

So this is a bug, but I don't have a platform for tests :/

You should be able to resolve this by passing the `-D RQ_LINKER=BSD` option to cmake

so in the libRaptorQ directory, try:
```
mkdir build
cd build
cmake -DRQ_LINKER=BSD ../
make
```

**Comment by twalk4821** [comment]
Still the same error. Although cmake did provide this warning:
```
  Manually-specified variables were not used by the project:

    RQ_LINKER
```

**Comment by LucaFulchir** [comment]
Oh. my bad.  
Old bug, tried to backport it and failed.
try to download again from the last link, you should get the updated version.

**Comment by twalk4821** [comment]
Yes! That did it! Thanks!
