### ISSUE TITLE
Regarding performance bottlenecks on libraptorq

### ISSUE THREAD

**Issue by andy-cf-lin** [LucaFulchir/libRaptorQ#14]
Hi Luca,

We’re currently integrating libraptorq to one of our internal data transfer infrastructure project. Since data is delivering through a lossy network, we’re aiming to use RaptorQ to reduce re-transmission overhead and make the whole system more scalable. The integration is rather straightforward, we forked libRaptorQ v1.0.0-prealpha to our project and integrate it through RFC interfaces. However, we hit CPU bound when we try to enlarge the block size and symbol size (will give encode parameters in details). The maximum bit rate we can reach when transmitting the encoded symbols in a streaming manner is only about 5 Mbps on c5d.2xlarge AWS instance (3.0 GHz Intel Xeon Platinum; each core at up to 3.5 GHz using Intel Turbo Boost Technology), and it occupies 100% CPU cycle doing all of the Eigen3 compute work. So obviously CPU is a big bottleneck. However, we want to have the block size and symbol size as long as possible since the network characteristic is that packet loss is a rare event (~<1%); however, the disruption may last for long time (in the degree of 10+ minutes). We’ve notice that the whole library is designed as asynchronous when performing encoding jobs and there’s also a threadpool being designed (we assumed this is for compute acceleration). We’re wondering how can we get the benefit of parallel computing in order to solve the performance bottlenecks by utilizing more CPU cores on encoding? It seems not quite clear to me on how the whole threadpool and asynchronous computing design works on the documentation and sample codes regarding to C integration. (test_c.c) We have to use C interface (RFC6330_v1) since most of our protocol implementation is in C. Also we’re not quite sure how sub-blocks encoding works in your implementations, can you also share some lights on this?

Cheers,
Andy

**Comment by LucaFulchir** [comment]
Hello, sorry for the terribly late response, I did not receive the github notification and the main development is on https://fenrirproject.org/Luker/libRaptorQ

Let's see:

* I would recommend the RAW api, as the RFC should be a bit slower and with unnecessary complexity (imho). The algorithm is the same, but you get to decide the block size, while it is more dificult to force something on the RFC interface.
* Unfortunately the complexity is cubic on the number of symbols in a block, so a big block size will mean a lot of time. Not much can be done in that regard. At least it is not much dependent on packet size. The maximum block size is about 56K, but if I remember correctly even at half of that I had to wait half an hour on my computer (corei7-3rd gen). So tuning the block size is essential.
* I suggest you compile with clang and with `DCMAKE_CXX_FLAGS="-mtune=native -march=native" -DCMAKE_C_FLAGS="-mtune=native -march=native"` this will compile with optimizations for your architecture, AVX included. without that you will probably compile or a generic x86_64. I have seen higher performance with this configuration. Next version will focus on speed but I can't give you estimates.
* The thread pool is not strictly needed as you should be able to run a synchronous computation by yourself. It is there as a simplification to manage parallel computation and re-computation. RaptorQ is a probabilistic algorithm, so there is a small chance that it will fail. Get more data, try again. Or you might want to launch multiple computation on the same block but with different data (`max_block_concurrency`, the second parameter in the `set_thread_pool` call). the RAW api does not use anything, so you are forced to build your own concurrency method. **TL;DR:** the thread pool is there for parallel computation o multiple blocks, not to speedup a single block (which is not possible in the RQ algorithm)
* sub_blocks are a weir thin in the rfc. Basically you give the data you want to the algorithm, and it automatically divides it in multiple blocks, depending on the parameters on the constructor. The input data is not fed to the algorithm as-is, but each block is further divided in sub-blocks. then the symbols in sub-symbols. Then it starts interleaving all the data, so that each symbol in output does not track a sequential part off the input. This is useful for lossy audio/video transmissions, but only if you know how to rebuild partial and interleaved data. Basically it is useless for anything else that is not lossy.  **TL;DR:** ignore the interleaving and use the RAW API

**Comment by LucaFulchir** [comment]
closing due to lack of news
