### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by diricse** [LucaFulchir/libRaptorQ#21]
int CRaptorQ::rawEnCode(const QByteArray &srcData,const float loss,quint16 &blocks,QByteArray &dst){
    int ret=-1;
    int dsize=srcData.length();
    if(dsize>0){
        //clear();
        std::vector<uint8_t> src(static_cast<size_t>(dsize),0);
        memcpy(src.data(),srcData.constData(),static_cast<size_t>(dsize));
        //计算符号个数
        size_t symbols=static_cast<size_t>(dsize);
        //设置块数
        blocks = static_cast<uint16_t>(RaptorQ::Block_Size::Block_10);
        for (auto blk : *RaptorQ::blocks) {
            if (static_cast<uint16_t> (blk) >= symbols) {
                blocks = static_cast<uint16_t> (blk);
                break;
            }
        }
        RaptorQ::Encoder<uint8_t*, uint8_t*> enc(static_cast<RaptorQ::Block_Size>(blocks), 1);
        if (enc.set_data (src.begin().base(), src.end().base()) != symbols) {
            qDebug()<<"Could not give data to the encoder ";
            return ret;
        }
        enc.compute();
        int overhead=getOverhead(loss);
        std::uniform_real_distribution<float> drop (0.0, 100.0);//设定可能丢包率
        int rq = overhead,deled=0,repair=0;
        auto rnd=getRandom();
        std::vector<std::vector<uint8_t>> encodes;
        for (auto sym_it = enc.begin_source(); sym_it != enc.end_source();++sym_it) {
            float dropped = drop (rnd);
            if (dropped <= loss) {
                ++rq;
                ++deled;
            }
            //char symbol[symbolsize]={0};
            std::vector<uint8_t> symbol(1,0);
            auto it = symbol.begin().base();
            (*sym_it) (it,symbol.end().base());
            encodes.emplace_back(std::move(symbol));
            //dst.append(reinterpret_cast<const char*>(symbol.data()),symbolsize);
        }

        auto sym_it = enc.begin_repair();
        for (; rq > 0 && sym_it != enc.end_repair (enc.max_repair());++sym_it)
        {
            float dropped = drop (rnd);
            if (dropped <= loss) {
                continue;
            }
            --rq;
            ++repair;
            std::vector<uint8_t> symbol(1,0);
            auto it = symbol.begin().base();
            (*sym_it) (it,symbol.end().base());
            encodes.emplace_back(std::move(symbol));
            //dst.append(reinterpret_cast<const char*>(symbol.data()),symbolsize);
        }
        if (sym_it == enc.end_repair (enc.max_repair())) {
            qDebug() << "Maybe losing " << loss << "% is too much?\n";
            return -2;
        }
        uint count=encodes.size();
        ret=static_cast<int>(count);
        dst.resize(ret);
        for(uint i=0;i<count;i++){
            memcpy(dst.data()+i,encodes[i].data(),1);
        }
        //endata=encodes;
    }
    return  ret;
}

if srcData length>220 bytes,(*sym_it) (it,symbol.end().base()) this code will excute long time,why?

**Comment by diricse** [comment]
template <typename Rnd_It, typename Fwd_It>
size_t Encoder<Rnd_It, Fwd_It>::encode (Fwd_It &output, const Fwd_It end,
                                                            const uint32_t id)
{
    if (_state == Enc_State::INIT_ERROR)
        return 0;
    // returns number of iterators written
    if (_state == Enc_State::FULL) {
        if (id >= _symbols) { // repair symbol
            if (!encoder.ready()) {
                if (!_single_wait.valid())
                    _single_wait = compute();
                _single_wait.wait();
            }
        }
        return encoder.Enc (id, output, end);
    }
    return 0;
}

I find this stoping is _single_wait.wait();

**Comment by LucaFulchir** [comment]
uhm...
please reformat your code on github, it's *atrocious* trying to read code that way
you can even use the syntax highlighter if you enclose it like this:
~~~
```cpp
your_code_here
```
~~~

I'll try to have a better look after that, but the first big thing I spot is right at the beginning:

```cpp
int dsize=srcData.length();
std::vector<uint8_t> src(static_cast<size_t>(dsize),0);
memcpy(src.data(),srcData.constData(),static_cast<size_t>(dsize));
size_t symbols=static_cast<size_t>(dsize);
```
Here you are working on a vector of X bytes. How long is that, actually?
That is a big question, because you are setting basically one symbol per byte.
You then search the smallest block that can fit all those symbols.
*That is a very bad idea.*
Symbols can (and should) have multiple bytes, take advantage of that.

The RaptorQ algorithm encoding/decoding is cubic on the number of symbols in a block.  
Once encoded, generating new repair symbols is linear, but not before.
So while a block of 100 symbols will barely take any time, a block of 1.000 will take much more than 10 times the block of 100 symbols.

Also, RaptorQ "only" defines blocks up to `56403`. I assure you that you don't want to get near even half of that.

Besides, you say:
> I find this stoping is _single_wait.wait();

Is your CPU running at least? Does it look like it's not doing anything?
please reformat your code in the previous messages, I'll look better after that.
I have not received other reports or deadlocks or anything similar, so for now I'll assume you are just trying to work with way too many symbols

**Comment by LucaFulchir** [comment]
Closing due to lack of news
